# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import functionplusone_pb2 as functionplusone__pb2


class QuickMathStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Plusone = channel.unary_unary(
                '/QuickMath/Plusone',
                request_serializer=functionplusone__pb2.number.SerializeToString,
                response_deserializer=functionplusone__pb2.plusonereply.FromString,
                )


class QuickMathServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Plusone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuickMathServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Plusone': grpc.unary_unary_rpc_method_handler(
                    servicer.Plusone,
                    request_deserializer=functionplusone__pb2.number.FromString,
                    response_serializer=functionplusone__pb2.plusonereply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'QuickMath', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QuickMath(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Plusone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/QuickMath/Plusone',
            functionplusone__pb2.number.SerializeToString,
            functionplusone__pb2.plusonereply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
